#+TITLE: Project README

This is a fun project for playing around with my strava data.

* Possible outputs
** Graphics
Chart maps and other fun graphs with various summary statistics (and routes)
** Maintenance 
Create an app that will keep track of wear and tear on components

* Maintenance App
The idea here is to create a lightweight way to track maintenance. I want to limit external dependencies and basically just get the minimum info from the activities and log it, with the ability then to see wear and tear by part, last time various maintenance tasks were performed, etc. 

** List of functions to include
- [X] Add/edit rider 
- [X] Add/edit bike
- [X] Add ride
- [X] Add/replace part
- [X] Add maintenance record
- [ ] Calculate miles on individual parts
- [ ] Calculate miles on bike as a whole
- [X] Calculate total miles for a rider
- [X] Fetch new rides from strava 
- [ ] Calculate wear on parts not in use
- [ ] Add a new bike to the db
- [ ] Export capabilities (e.g. export an entire maintenance log to csv)

** Other concerns
- [X] Units need to be converted to miles/ft (maybe? or at least km and m) (also seconds are not a good unit of time)
- [ ] time format for testing if activities are new
- [ ] How best to store the secret stuff?
- [ ] How to deal with alphanumeric ids and something intelligible?
- [X] Now that I've switched to a single rider database, do i need the link to bikes?
- [X] Rides don't currently have dates
- [X] Need to filter only rides when querying strava (i.e. eliminate runs and other types of activities)
- [X] Don't need so much info for the rider

* Installation/Usage Requirements
** stravalib
Just a good old =pip3.6 install --user stravalib=
